### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by Wraith2** [somdoron/AsyncIO#14]
I've forked the current codebase with the intent to investigate a performance profiler hotspot but I can't get it to build. The project seems to be hardcoded into a .netstandard 1.3 build configuration and I've no ability to change it, to anything. I'm using VS 2017.2

Can you give me some guidance how I would build a full framework build to try out some options?

**Comment by wmjordan** [comment]
You may need to install the .NET Core development packages.

If you don't want .netstandard support at all, open the csproj file with a text editor and remove `netstandard1.3;` from it. Afterward, you may compile it and generate the .NET Framework libraries.

**Comment by somdoron** [comment]
The project is still using project.json. So you might want to edit it before opening with visual studio. Visual studio should covert it to csproj
